# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
# %tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [3]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [4]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.model_selection import train_test_split

In [5]:
df = sklearn.datasets.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [6]:
X = df.data

In [7]:
y = df.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [8]:
size = 0.25
seed = 7
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=size, random_state=seed)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [9]:
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [10]:
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [11]:
model.add(tf.keras.layers.Dense(units=3, input_shape=(4,), activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [12]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [14]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100)

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 3s 27ms/sample - loss: 2.6440 - accuracy: 0.3482 - val_loss: 1.8549 - val_accuracy: 0.2895
Epoch 2/100
112/112 [==============================] - 0s 616us/sample - loss: 1.6175 - accuracy: 0.3304 - val_loss: 1.4040 - val_accuracy: 0.1579
Epoch 3/100
112/112 [==============================] - 0s 697us/sample - loss: 1.3306 - accuracy: 0.1607 - val_loss: 1.2363 - val_accuracy: 0.1053
Epoch 4/100
112/112 [==============================] - 0s 670us/sample - loss: 1.2189 - accuracy: 0.1696 - val_loss: 1.1956 - val_accuracy: 0.1316
Epoch 5/100
112/112 [==============================] - 0s 643us/sample - loss: 1.1715 - accuracy: 0.1964 - val_loss: 1.1616 - val_accuracy: 0.2105
Epoch 6/100
112/112 [==============================] - 0s 473us/sample - loss: 1.1267 - accuracy: 0.2054 - val_loss: 1.1215 - val_accuracy: 0.2632
Epoch 7/100
112/112 [==============================] - 0s 527us/sample - l

112/112 [==============================] - 0s 429us/sample - loss: 0.5372 - accuracy: 0.7589 - val_loss: 0.6137 - val_accuracy: 0.6053
Epoch 57/100
112/112 [==============================] - 0s 438us/sample - loss: 0.5366 - accuracy: 0.7321 - val_loss: 0.5989 - val_accuracy: 0.7632
Epoch 58/100
112/112 [==============================] - 0s 527us/sample - loss: 0.5299 - accuracy: 0.7946 - val_loss: 0.5952 - val_accuracy: 0.7632
Epoch 59/100
112/112 [==============================] - 0s 545us/sample - loss: 0.5281 - accuracy: 0.8482 - val_loss: 0.5997 - val_accuracy: 0.6579
Epoch 60/100
112/112 [==============================] - 0s 473us/sample - loss: 0.5273 - accuracy: 0.7679 - val_loss: 0.5959 - val_accuracy: 0.7105
Epoch 61/100
112/112 [==============================] - 0s 482us/sample - loss: 0.5211 - accuracy: 0.7589 - val_loss: 0.5895 - val_accuracy: 0.7368
Epoch 62/100
112/112 [==============================] - 0s 393us/sample - loss: 0.5198 - accuracy: 0.7768 - val_loss: 0.5823 

## Question 10

### Make predictions
- Predict labels on one row

In [15]:
y_pred = model.predict(x_test[0:1])

In [16]:
y_pred

array([[0.0247709 , 0.3185221 , 0.65670705]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [17]:
y_test[0:1]

array([[0., 0., 1.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [18]:
# %tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [19]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [20]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [21]:
# run this cell to upload file if you are using google colab
# from google.colab import files
# files.upload()

In [22]:
df = pd.read_csv('prices.csv')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [24]:
df.drop(labels=['date', 'symbol'], axis=1, inplace=True)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 5 columns):
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5)
memory usage: 32.5 MB


## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [26]:
df_sample = df.head(1000)

In [27]:
df_sample.head(15)

open       close         low        high     volume
0   123.430000  125.839996  122.309998  126.250000  2163600.0
1   125.239998  119.980003  119.940002  125.540001  2386400.0
2   116.379997  114.949997  114.930000  119.739998  2489500.0
3   115.480003  116.620003  113.500000  117.440002  2006300.0
4   117.010002  114.970001  114.089996  117.330002  1408600.0
5   115.510002  115.550003  114.500000  116.059998  1098000.0
6   116.459999  112.849998  112.589996  117.070000   949600.0
7   113.510002  114.379997  110.050003  115.029999   785300.0
8   113.330002  112.529999  111.919998  114.879997  1093700.0
9   113.660004  110.379997  109.870003  115.870003  1523500.0
10  109.059998  109.300003  108.320000  111.599998  1653900.0
11  109.730003  110.000000  108.320000  110.580002   944300.0
12  111.879997  111.949997  110.190002  112.949997   744900.0
13  111.320000  110.120003  110.000000  114.629997   703800.0
14  110.419998  111.000000  107.300003  111.400002   563100.0

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [28]:
x = df_sample.drop('volume', axis=1)
y = df_sample['volume']/1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [29]:
X = x.to_numpy()

In [30]:
Y = y.to_numpy()

In [31]:
X = X.astype('float32')
Y = Y.astype('float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [32]:
X = tf.math.l2_normalize(X)

In [33]:
print('Number of examples: ', X.shape[0])
print('Number of features for each example: ', X.shape[1])
print('Shape of actual prices data: ', df_sample.shape)

Number of examples:  1000
Number of features for each example:  4
Shape of actual prices data:  (1000, 5)


## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [34]:
W = tf.zeros(shape=(4, 1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [35]:
@tf.function
def prediction(features, W, b):
    y_pred = tf.add(tf.matmul(features, W), b)
    return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [36]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [37]:
@tf.function
def train(x, y_actual, w, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [38]:
for i in range(100):
    W, b = train(X, Y, W, b)
    print('Current Training Loss on iteration', i, loss(Y, prediction(X, W, b)).numpy())

Current Training Loss on iteration 0 236.16759
Current Training Loss on iteration 1 235.09299
Current Training Loss on iteration 2 234.06102
Current Training Loss on iteration 3 233.06998
Current Training Loss on iteration 4 232.11781
Current Training Loss on iteration 5 231.20381
Current Training Loss on iteration 6 230.32585
Current Training Loss on iteration 7 229.48265
Current Training Loss on iteration 8 228.67297
Current Training Loss on iteration 9 227.89539
Current Training Loss on iteration 10 227.14832
Current Training Loss on iteration 11 226.43114
Current Training Loss on iteration 12 225.74234
Current Training Loss on iteration 13 225.0808
Current Training Loss on iteration 14 224.44553
Current Training Loss on iteration 15 223.835
Current Training Loss on iteration 16 223.24931
Current Training Loss on iteration 17 222.68655
Current Training Loss on iteration 18 222.14595
Current Training Loss on iteration 19 221.62688
Current Training Loss on iteration 20 221.12842
Curre

### Observe values of Weight
- Print the updated values

In [39]:
W.numpy()

array([[0.05478281],
       [0.05488191],
       [0.05422735],
       [0.05533117]], dtype=float32)

### Observe values of Bias
- Print the updated values

In [40]:
b.numpy()

array([4.607657], dtype=float32)